name: TheActionDev
on:
  push:
    branches:
      - main # your default branch

jobs:
  operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Synchronising local article with dev.to
        uses: ful1e5/TheActionDev@v2
        with:
          api-key: ${{ secrets.DEVTO_API_KEY }} # Store your 'api-key' in Github Secret
          directory: ./articles # Your articles directory
          ignore: Ignore-me.md # Markdown file you wan't to ignore. Multiple files separated by ,(comma)
